version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_BACKEND_BASE_URL: ${APP_BACKEND_BASE_URL}
      SMS_API_TOKEN: ${SMS_API_TOKEN}
    restart: always
    networks:
      - mediamate-network

networks:
  mediamate-network:
    external: true
