services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-mediamate
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_BACKEND_BASE_URL: ${APP_BACKEND_BASE_URL}
      SMS_API_TOKEN: ${SMS_API_TOKEN}
      EMAIL_USERNAME: ${EMAIL_USERNAME}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    networks:
      - network-mediamate

networks:
  network-mediamate:
    external: true
